### ISSUE TITLE
Add functions to random_names

### ISSUE THREAD

**Issue by micha003** [micha003/teachers-tool#5]
- you can choose, if only one name should be chosen or all names were directly sorted in groups

**Comment by micha003** [comment]
The main function are standing. But get_numnames is not working...

The code is in the extensions-branch

**Comment by micha003** [comment]
deleted some useless functions and fixing other bugs like in the _randomizing_groups_ - function
But it's less buggy 😄

**Comment by lana80** [comment]
Hi!

I will help you !!!

**Comment by micha003** [comment]
I think I will cut the work on _randomizing_groups_ , because I have wasted much time and hadn't found a solution. But there will be other functions!
